"""Markdown rendering of the research memo."""

from __future__ import annotations

from typing import Any

from etflab.report.memo import (
    Callout,
    CodeBlock,
    Figure,
    KeyValues,
    Memo,
    Paragraph,
    Table,
    build_memo,
    format_frame,
)

CALLOUT_PREFIX = {"finding": "**Finding.**", "caution": "**Caution.**", "method": "**Method.**"}


def _table_to_markdown(table: Table) -> str:
    frame = format_frame(table)
    index_label = table.index_label or (frame.index.name or "")
    header = [index_label, *[str(c) for c in frame.columns]]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for index, row in frame.iterrows():
        lines.append("| " + " | ".join([str(index), *[str(v) for v in row]]) + " |")
    body = "\n".join(lines)
    out = f"**{table.title}**\n\n{body}"
    if table.note:
        out += f"\n\n_{table.note}_"
    return out


def render_markdown(study: Any, manifest: Any, figure_dir: str = "figures") -> str:
    """Render the full memo as GitHub-flavoured Markdown."""
    memo: Memo = build_memo(study, manifest)
    parts: list[str] = [f"# {memo.title}", "", f"_{memo.subtitle}_", ""]
    parts.append(
        "> Generated by `etf-lab study`. Run id `{run_id}` · data `{data_source}` · fingerprint `{fingerprint}` · "
        "{generated}".format(**memo.meta)
    )
    parts.append("")
    parts.append("## Contents")
    parts.append("")
    for section in memo.sections:
        anchor = section.anchor or section.title.lower().replace(" ", "-")
        parts.append(f"- [{section.title}](#{anchor})")
    parts.append("")

    for section in memo.sections:
        anchor = section.anchor or section.title.lower().replace(" ", "-")
        parts.append(f'<a id="{anchor}"></a>')
        parts.append("")
        parts.append(f"## {section.title}")
        parts.append("")
        for block in section.blocks:
            if isinstance(block, Paragraph):
                parts.append(block.text)
            elif isinstance(block, Callout):
                prefix = CALLOUT_PREFIX.get(block.kind, "**Note.**")
                body = block.text.replace("\n", "\n> ")
                parts.append(f"> {prefix} {block.title}\n>\n> {body}")
            elif isinstance(block, Table):
                parts.append(_table_to_markdown(block))
            elif isinstance(block, Figure):
                parts.append(f"![{block.caption}]({figure_dir}/{block.name}.png)\n\n_{block.caption}_")
            elif isinstance(block, KeyValues):
                rows = "\n".join(f"| {k} | {v} |" for k, v in block.items)
                parts.append(f"**{block.title}**\n\n| | |\n|---|---|\n{rows}")
            elif isinstance(block, CodeBlock):
                parts.append(f"```{block.language}\n{block.text}\n```")
            parts.append("")
    return "\n".join(parts).rstrip() + "\n"
