#!/usr/bin/env python3
"""Regenerate the committed figures and the results table in the README.

The README quotes numbers. Numbers in a README rot the moment the code changes,
and a rotted README is worse than no README because it is confidently wrong.
So the numbers are generated: this script runs the shipped experiment, writes the
figures into ``docs/figures/``, and rewrites the block between the
``RESULTS-TABLE`` markers in README.md.

``make figures`` runs it. CI checks that running it leaves the tree unchanged, so
a change to the model that moves the headline numbers cannot be merged with a
README that still quotes the old ones.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from etflab.config import ExperimentConfig  # noqa: E402
from etflab.data import load_panel, run_quality_gates  # noqa: E402
from etflab.report.figures import make_figures  # noqa: E402
from etflab.research import run_study  # noqa: E402

START = "<!-- RESULTS-TABLE:START -->"
END = "<!-- RESULTS-TABLE:END -->"

ROW_METRICS = (
    ("tracking_error", "Tracking error", "{:.2%}"),
    ("correlation", "Correlation", "{:.3f}"),
    ("down_capture", "Down capture", "{:.2f}"),
    ("annual_turnover", "Turnover / yr", "{:.1%}"),
)


def build_table(study) -> str:
    metrics = study.race.metrics.sort_values("tracking_error")
    floor = study.panel.truth.irreducible_te_annual if study.panel.truth is not None else None

    lines = [
        "| Strategy | Tracking error | Correlation | Down capture | Turnover / yr | vs. equal weight |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, row in metrics.iterrows():
        comparison = study.race.comparisons.get(name)
        if comparison is None:
            verdict = "benchmark"
        elif comparison.significantly_better:
            verdict = f"{comparison.te_difference:+.2%} (significant)"
        elif comparison.ci.excludes_zero:
            verdict = f"{comparison.te_difference:+.2%} (worse)"
        else:
            verdict = f"{comparison.te_difference:+.2%} (not distinguishable)"
        label = f"**{name}**" if name == study.race.best else name
        lines.append(
            f"| {label} | {row['tracking_error']:.2%} | {row['correlation']:.3f} | "
            f"{row.get('down_capture', float('nan')):.2f} | {row.get('annual_turnover', float('nan')):.1%} | {verdict} |"
        )
    if floor is not None:
        lines.append(
            f"| _irreducible floor_ | _{floor:.2%}_ | _1.000_ | _--_ | _--_ | "
            "_the best any long-only basket of these candidates can do_ |"
        )

    parts = [
        "\n".join(lines),
        "",
        f"**Verdict.** {study.race.verdict}",
        "",
    ]
    if study.sweep is not None:
        parts.append(
            f"**Overfitting.** Probability of backtest overfitting across {len(study.sweep.frame)} "
            f"configurations: **{study.sweep.pbo.pbo:.0%}**, against a matched pure-noise reference of "
            f"{study.sweep.noise_pbo:.0%}. {study.sweep.pbo.verdict.capitalize()}."
        )
        parts.append("")
    if study.recovery is not None:
        parts.append(f"**Consistency.** {study.recovery.interpretation}")
        parts.append("")
    parts.append(
        f"<sub>Generated by `scripts/build_docs.py` from run `{study.config.semantic_hash()}` on "
        f"{study.panel.source} data (fingerprint `{study.panel.fingerprint()}`), "
        f"{len(study.race.results[study.race.best].daily):,} out-of-sample days. "
        "Reproduce with `make study`.</sub>"
    )
    return "\n".join(parts)


def rewrite_readme(table: str, readme: Path) -> bool:
    text = readme.read_text()
    if START not in text or END not in text:
        raise SystemExit(f"{readme} is missing the {START} / {END} markers.")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = f"{head}{START}\n{table}\n{END}{tail}"
    if updated == text:
        return False
    readme.write_text(updated)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the docs would change")
    parser.add_argument("--output", default=str(ROOT / "outputs"))
    args = parser.parse_args()

    config = ExperimentConfig(output_dir=args.output).validate()
    panel = load_panel(config)
    quality = run_quality_gates(panel, min_obs=config.train_days + config.rebalance_days)
    print(f"Running the shipped experiment on {panel.n_obs:,} observations…", flush=True)
    study = run_study(config, panel, quality, progress=lambda message: print(f"  {message}", flush=True))

    figures_dir = ROOT / "docs" / "figures"
    if args.check:
        staging = ROOT / ".docs-check"
        shutil.rmtree(staging, ignore_errors=True)
        make_figures(study, staging)
        readme_changed = rewrite_readme(build_table(study), ROOT / "README.md")
        shutil.rmtree(staging, ignore_errors=True)
        if readme_changed:
            print("README results table was out of date and has been rewritten.", file=sys.stderr)
            return 1
        print("Docs are up to date.")
        return 0

    produced = make_figures(study, figures_dir)
    for name, path in sorted(produced.items()):
        print(f"  wrote {path.relative_to(ROOT)} ({name})")
    changed = rewrite_readme(build_table(study), ROOT / "README.md")
    print("README results table " + ("updated." if changed else "already current."))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
