#!/usr/bin/env python3
"""Regenerate the committed figures and the results table in the README.

The README quotes numbers. Numbers in a README rot the moment the code changes,
and a rotted README is worse than no README because it is confidently wrong.
So the numbers are generated: this script runs the shipped experiment, writes the
figures into ``docs/figures/``, and rewrites the block between the
``RESULTS-TABLE`` markers in README.md.

``make figures`` runs it. CI checks that running it leaves the tree unchanged, so
a change to the model that moves the headline numbers cannot be merged with a
README that still quotes the old ones.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from etflab.config import ExperimentConfig  # noqa: E402
from etflab.data import load_panel, run_quality_gates  # noqa: E402
from etflab.report.figures import make_figures  # noqa: E402
from etflab.research import run_study  # noqa: E402

START = "<!-- RESULTS-TABLE:START -->"
END = "<!-- RESULTS-TABLE:END -->"

ROW_METRICS = (
    ("tracking_error", "Tracking error", "{:.2%}"),
    ("correlation", "Correlation", "{:.3f}"),
    ("down_capture", "Down capture", "{:.2f}"),
    ("annual_turnover", "Turnover / yr", "{:.1%}"),
)


def build_table(study) -> str:
    metrics = study.race.metrics.sort_values("tracking_error")
    floor = study.panel.truth.irreducible_te_annual if study.panel.truth is not None else None

    lines = [
        "| Strategy | Tracking error | Correlation | Down capture | Turnover / yr | vs. equal weight |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, row in metrics.iterrows():
        comparison = study.race.comparisons.get(name)
        if comparison is None:
            verdict = "benchmark"
        elif comparison.significantly_better:
            verdict = f"{comparison.te_difference:+.2%} (significant)"
        elif comparison.ci.excludes_zero:
            verdict = f"{comparison.te_difference:+.2%} (worse)"
        else:
            verdict = f"{comparison.te_difference:+.2%} (not distinguishable)"
        label = f"**{name}**" if name == study.race.best else name
        lines.append(
            f"| {label} | {row['tracking_error']:.2%} | {row['correlation']:.3f} | "
            f"{row.get('down_capture', float('nan')):.2f} | {row.get('annual_turnover', float('nan')):.1%} | {verdict} |"
        )
    if floor is not None:
        lines.append(
            f"| _irreducible floor_ | _{floor:.2%}_ | _1.000_ | _--_ | _--_ | "
            "_the best any long-only basket of these candidates can do_ |"
        )

    parts = [
        "\n".join(lines),
        "",
        f"**Verdict.** {study.race.verdict}",
        "",
    ]
    if study.sweep is not None:
        parts.append(
            f"**Overfitting.** Probability of backtest overfitting across {len(study.sweep.frame)} "
            f"configurations: **{study.sweep.pbo.pbo:.0%}**, against a matched pure-noise reference of "
            f"{study.sweep.noise_pbo:.0%}. {study.sweep.pbo.verdict.capitalize()}."
        )
        parts.append("")
    if study.recovery is not None:
        parts.append(f"**Consistency.** {study.recovery.interpretation}")
        parts.append("")
    parts.append(
        f"<sub>Generated by `scripts/build_docs.py` from run `{study.config.semantic_hash()}` on "
        f"{study.panel.source} data (fingerprint `{study.panel.fingerprint()}`), "
        f"{len(study.race.results[study.race.best].daily):,} out-of-sample days. "
        "Reproduce with `make study`.</sub>"
    )
    return "\n".join(parts)


def current_block(readme: Path) -> str:
    text = readme.read_text()
    if START not in text or END not in text:
        raise SystemExit(f"{readme} is missing the {START} / {END} markers.")
    return text.split(START, 1)[1].split(END, 1)[0].strip("\n")


def rewrite_readme(table: str, readme: Path) -> bool:
    text = readme.read_text()
    if START not in text or END not in text:
        raise SystemExit(f"{readme} is missing the {START} / {END} markers.")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = f"{head}{START}\n{table}\n{END}{tail}"
    if updated == text:
        return False
    readme.write_text(updated)
    return True


_NUMBER = re.compile(r"-?\d[\d,]*(?:\.\d+)?(?:e[-+]?\d+)?")
_CODE = re.compile(r"`[^`]*`")


def _decimals(token: str) -> int:
    """How many decimal places a printed number carries."""
    if "e" in token.lower():
        return 0
    return len(token.split(".")[1]) if "." in token else 0


def _skeleton_and_numbers(block: str) -> tuple[str, list[tuple[float, int]]]:
    """Split a block into its non-numeric skeleton and the numbers it quotes.

    Each number is returned with the precision it was printed at. Numbers inside
    backticks (hashes, fingerprints, run ids) are part of the skeleton -- they
    are identifiers, and an identifier that changed is stale.
    """
    numbers: list[tuple[float, int]] = []

    def capture(match: re.Match[str]) -> str:
        token = match.group()
        numbers.append((float(token.replace(",", "")), _decimals(token)))
        return "#"

    pieces: list[str] = []
    cursor = 0
    for code in _CODE.finditer(block):
        pieces.append(_NUMBER.sub(capture, block[cursor : code.start()]))
        pieces.append(code.group())
        cursor = code.end()
    pieces.append(_NUMBER.sub(capture, block[cursor:]))
    return "".join(pieces), numbers


def tables_match(committed: str, generated: str, *, last_digit_units: float = 3.0) -> tuple[bool, str]:
    """Do two results blocks say the same thing?

    The skeleton -- every word, every identifier, the strategy ordering, the
    verdict's clauses -- must match exactly. A changed word means the conclusion
    changed.

    Numbers get a tolerance derived purely from the precision they were printed
    at: the last printed digit may move by a few units, the rest must hold. So
    "5.73%" tolerates 5.76 but not 5.79, "0.083" tolerates 0.086, and a rank
    statistic printed as "24%" tolerates 27. No relative slack: a one-percent
    move in a tracking error is a real change, not float noise. This is the honest amount of slack: a different CPU and
    BLAS legitimately lands an interior-point solve a few ULPs away, which
    re-orders near-tied configurations and wobbles a rank-based statistic by a
    point or two, while a real change in a result still moves the digits that
    are meant to be read.
    """
    skeleton_a, numbers_a = _skeleton_and_numbers(committed)
    skeleton_b, numbers_b = _skeleton_and_numbers(generated)
    if skeleton_a != skeleton_b:
        return False, "the wording, ordering or identifiers changed"
    if len(numbers_a) != len(numbers_b):
        return False, f"{len(numbers_a)} numbers committed, {len(numbers_b)} generated"
    worst = 0.0
    for (a, decimals), (b, _) in zip(numbers_a, numbers_b, strict=True):
        limit = last_digit_units * 10.0 ** (-decimals)
        gap = abs(a - b)
        worst = max(worst, gap)
        if gap > limit + 1e-12:
            return False, f"a number moved from {a:g} to {b:g} (tolerance {limit:g})"
    return True, f"largest numeric deviation {worst:g}"


def show_diff(committed: str, generated: str) -> None:
    diff = difflib.unified_diff(
        committed.splitlines(), generated.splitlines(), "README.md (committed)", "README.md (generated)", lineterm=""
    )
    print("\n".join(diff), file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the docs would change")
    parser.add_argument("--output", default=str(ROOT / "outputs"))
    args = parser.parse_args()

    config = ExperimentConfig(output_dir=args.output).validate()
    panel = load_panel(config)
    quality = run_quality_gates(panel, min_obs=config.train_days + config.rebalance_days)
    print(f"Running the shipped experiment on {panel.n_obs:,} observations…", flush=True)
    study = run_study(config, panel, quality, progress=lambda message: print(f"  {message}", flush=True))

    figures_dir = ROOT / "docs" / "figures"
    if args.check:
        committed = current_block(ROOT / "README.md")
        generated = build_table(study)
        ok, reason = tables_match(committed, generated)
        if not ok:
            print(f"README results table is stale: {reason}.", file=sys.stderr)
            show_diff(committed, generated)
            print("Run `make figures` and commit the result.", file=sys.stderr)
            return 1
        print(f"Docs are up to date ({reason}).")
        return 0

    produced = make_figures(study, figures_dir)
    for name, path in sorted(produced.items()):
        print(f"  wrote {path.relative_to(ROOT)} ({name})")
    changed = rewrite_readme(build_table(study), ROOT / "README.md")
    print("README results table " + ("updated." if changed else "already current."))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
